### ISSUE TITLE
Request for Qt 5 release

### ISSUE THREAD

**Issue by ilovezfs** [flavio/qjson#95] opened 2016-11-26 05:51 UTC
Hi,

Homebrew maintainer here.

Just a heads up that this project has now been "boneyarded" in Homebrew due to lack of Qt 5 support in a tagged release. This means that qjson was moved from https://github.com/Homebrew/homebrew-core to https://github.com/Homebrew/homebrew-boneyard, and has effectively been removed from Homebrew for all intents and purposes.

My understanding is that the qjson master branch _does_  actually have Qt 5 support, so we could reinstate qjson in Homebrew if a new version tag with Qt 5 support could be pushed to GitHub.

Thanks for your help and please let us know if you have any questions.

**Comment by flavio** [comment] 2016-11-29 15:47
Duplicate of https://github.com/flavio/qjson/issues/49
Fixed with 0.9.0 release

**Closed by flavio** 2016-11-29 15:47 UTC
